import {Footer} from "@/components/ui/Footer";
import {FC, ReactNode} from "react";
import Head from "next/head";

interface IAuthLayout {
    children: ReactNode,
    title: string
}

export const AuthLayout: FC<IAuthLayout> = ({children, title}) => {
    return (
        <>
            <Head>
                <title>{title} | Ecommerce</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <main>
                <section className="bg-gray-50 dark:bg-gray-900">
                    <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
                        <div
                            className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                            <div className="p-6 space-y-4 md:space-y-6 sm:p-8">
                                {children}
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        </>
    )
}