import {ILayout} from "@/components/layouts/layout.types";
import favicon from "@/assets/images/favicon.png";
import Head from "next/head";
import {FC} from "react";

// Обертка для определенных страниц
export const AuthLayout: FC<ILayout> = ({children, title}) => {
    return (
        <>
            <Head>
                <title>{title} | Ecommerce</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel={'shortcut icon'} href={favicon.src} type={'image/png'}/>
            </Head>
            <main className={"min-h-screen"}>
                <section className="bg-gray-50 dark:bg-gray-900">
                    <div className="flex flex-col items-center justify-center px-2 py-4 mx-auto h-screen lg:py-0">
                        <div
                            className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                            <div className="p-2 space-y-4 md:space-y-6 sm:p-5">
                                {children}
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        </>
    )
}