import Head from "next/head";
import {FC, ReactNode} from "react";
import {Footer} from "@/components/ui/Footer";

interface IAuthLayout {
    children: ReactNode,
    title: string
}

export const AuthLayout: FC<IAuthLayout> = ({children, title}) => {
    return (
        <>
            <Head>
                <title>{title} | Ecommerce</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <main className={""}>
                {children}
            </main>
            <Footer/>
        </>
    )
}