import {CookiesConsentPopup} from "@/components/ui/Popups/CookiesConsentPopup";
import {ILayout} from "@/components/layouts/layout.types";
import favicon from '@/assets/images/favicon.png'
import {Header} from "../ui/Header";
import {Footer} from "../ui/Footer";
import Head from "next/head";
import {FC} from "react";

// Обертка для определенных страниц
export const MainLayout: FC<ILayout> = ({children, title}) => {
    return (
        <>
            <Head>
                <title>{title} | Ecommerce</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel={'shortcut icon'} href={favicon.src} type={'image/png'}/>
            </Head>
            <Header/>
            <main className={"min-h-screen p-5"}>
                {children}
            </main>
            <Footer/>
            <CookiesConsentPopup/>
        </>
    )
}

